// The Notebook Verification Report, typeset as a PDF.
//
// This is the document that gets sent to somebody — into a WhatsApp chat, or
// saved and forwarded. So it carries the same things the on-screen report
// carries and, importantly, the same caveats: the pupil-side note, the undated
// note and the disputed note travel with the figures rather than being screen
// furniture that falls off on the way out. A report that loses "this notebook
// had no recorded date, so it is not counted against her" on its way into a
// chat is a report that says something the system does not mean.
//
// Pure and deterministic. No React, no I/O.

import { Pdf, textWidth, wrapText } from "./pdf";
import { splitStatus } from "./attribution";
import { CLASS_BAND_LABEL, type ClassBand } from "./observations";

const NAVY: [number, number, number] = [0.039, 0.247, 0.420];
const TEAL: [number, number, number] = [0.008, 0.408, 0.455];
const GREY: [number, number, number] = [0.341, 0.384, 0.435];
const RULE: [number, number, number] = [0.80, 0.79, 0.76];
const GOLD: [number, number, number] = [0.945, 0.769, 0.541];

export interface PdfStudent {
  name: string;
  days: number | null;
  remark: string;
  statusTag?: string;
  band?: string;
  obs?: string[] | null;
}

export interface PdfReport {
  campus: string;
  coordinatorName: string;
  date: string;
  teacher: string;
  cls: string;
  subject: string;
  classBand?: ClassBand | null;
  students: PdfStudent[];
  recs: string[];
  finalObservation: string;
  principalSummary: string;
}

const M = 48;                    // page margin
const COL = [130, 52, 128, 0];   // Student, Days, Status, Observations (last = remainder)

export function buildReportPdf(r: PdfReport): Uint8Array {
  const pdf = new Pdf();
  const contentW = pdf.width - M * 2;
  COL[3] = contentW - COL[0] - COL[1] - COL[2];

  let y = 0;
  let page = 0;

  const footer = () => {
    pdf.line(M, 54, pdf.width - M, 54, RULE);
    pdf.text(`Academics, ${r.campus} — generated by NQAS`, M, 42, { size: 8, color: GREY });
    const label = `Page ${page}`;
    pdf.text(label, pdf.width - M - textWidth(label, 8), 42, { size: 8, color: GREY });
  };

  // Every page opens with the same letterhead band, so a page forwarded on its
  // own still says which school and which campus it came from.
  const startPage = (first: boolean) => {
    if (!first) pdf.newPage();
    page += 1;
    pdf.rect(0, pdf.height - 76, pdf.width, 76, NAVY);
    pdf.rect(0, pdf.height - 79, pdf.width, 3, GOLD);
    pdf.text("Krishna Vikash Group of CBSE Schools", M, pdf.height - 40,
      { size: 15, bold: true, color: [1, 1, 1] });
    pdf.text(r.campus, M, pdf.height - 58, { size: 10, color: [0.945, 0.769, 0.541] });
    y = pdf.height - 108;
  };

  /** Make sure `need` points remain above the footer; otherwise break. */
  const ensure = (need: number) => {
    if (y - need < 72) { footer(); startPage(false); }
  };

  const heading = (t: string) => {
    ensure(34);
    y -= 6;
    pdf.text(t, M, y, { size: 11.5, bold: true, color: TEAL });
    y -= 15;
  };

  const para = (t: string, size = 9.5) => {
    for (const line of wrapText(t, contentW, size)) {
      ensure(size + 5);
      pdf.text(line, M, y, { size });
      y -= size + 4;
    }
  };

  startPage(true);

  // ---- title ----
  const title = "Notebook Verification Report";
  pdf.text(title, (pdf.width - textWidth(title, 16, true)) / 2, y, { size: 16, bold: true, color: NAVY });
  y -= 26;

  // ---- meta pairs, two per row ----
  const meta: [string, string][] = [
    ["Teacher", r.teacher],
    ["Class", r.cls],
    ["Subject", r.subject],
    ["Verification Date", r.date],
    ["Coordinator", r.coordinatorName],
    ["Notebooks Sampled", String(r.students.length)],
  ];
  if (r.classBand) meta.push(["Class Band", CLASS_BAND_LABEL[r.classBand]]);

  for (let i = 0; i < meta.length; i += 2) {
    ensure(16);
    const half = contentW / 2;
    [meta[i], meta[i + 1]].forEach((pair, k) => {
      if (!pair) return;
      const x = M + k * half;
      pdf.text(`${pair[0]}:`, x, y, { size: 9, bold: true, color: NAVY });
      const lw = textWidth(`${pair[0]}: `, 9, true);
      pdf.text(clip(pair[1], half - lw - 8, 9), x + lw, y, { size: 9 });
    });
    y -= 15;
  }
  y -= 6;

  // ---- the table ----
  const xs = [M, M + COL[0], M + COL[0] + COL[1], M + COL[0] + COL[1] + COL[2]];

  const tableHead = () => {
    ensure(26);
    pdf.rect(M, y - 6, contentW, 20, NAVY);
    const h = ["Student", "Days", "Checking Status", "Observations"];
    h.forEach((t, i) => pdf.text(t, xs[i] + 5, y, { size: 8.5, bold: true, color: [1, 1, 1] }));
    y -= 24;
  };
  tableHead();

  for (const s of r.students) {
    const sp = splitStatus(s, r.classBand);

    // Flags travel with the status, each labelled with whose they are — the
    // whole point of the split is lost if they arrive as an undifferentiated
    // list beside a teacher's name.
    const statusLines = [
      sp.tag,
      ...sp.teacherFlags.map((f) => `${f} · teacher`),
      ...sp.disputedFlags.map((f) => `${f} · date disagrees`),
      ...sp.pupilFlags.map((f) => `${f} · pupil`),
    ];
    const nameLines = wrapText(s.name || "—", COL[0] - 10, 9);
    const statusWrapped = statusLines.flatMap((t, i) => wrapText(t, COL[2] - 10, i === 0 ? 9 : 7.5, i === 0));
    const remarkLines = wrapText(s.remark || "—", COL[3] - 10, 8.5);
    // Row padding and the rule position are tied together: the separator has to
    // clear the descenders of this row and stay well above the cap height of the
    // next, or it draws a line through somebody's name.
    const rows = Math.max(nameLines.length, statusWrapped.length, remarkLines.length);
    const rowH = rows * 11 + 14;

    if (y - rowH < 72) { footer(); startPage(false); tableHead(); }

    const top = y + 8;
    nameLines.forEach((t, i) => pdf.text(t, xs[0] + 5, y - i * 11, { size: 9 }));
    pdf.text(s.days == null ? "—" : String(s.days), xs[1] + COL[1] / 2 - 8, y, { size: 9 });
    statusWrapped.forEach((t, i) =>
      pdf.text(t, xs[2] + 5, y - i * 11, { size: i === 0 ? 9 : 7.5, bold: i === 0, color: i === 0 ? NAVY : GREY }));
    remarkLines.forEach((t, i) => pdf.text(t, xs[3] + 5, y - i * 11, { size: 8.5 }));

    y -= rowH;
    pdf.line(M, y + 12, pdf.width - M, y + 12, RULE);
    void top;
  }

  y -= 8;

  // ---- the caveats, carried with the figures ----
  const pupilFlagged = r.students.filter((s) => splitStatus(s, r.classBand).pupilFlags.length).length;
  const undated = r.students.filter((s) => splitStatus(s, r.classBand).unknown).length;
  const disputed = r.students.filter((s) => splitStatus(s, r.classBand).disputedFlags.length).length;

  const notes: string[] = [];
  if (pupilFlagged) {
    notes.push(`The status shown is the teacher's checking standing, taken from days since last checked. ` +
      `${pupilFlagged} notebook${pupilFlagged === 1 ? "" : "s"} also ` +
      `${pupilFlagged === 1 ? "carries a flag" : "carry flags"} raised by the pupil's own work — ` +
      `recorded here, but never counted against the teacher.`);
  }
  if (undated) {
    notes.push(`${undated} notebook${undated === 1 ? " has" : "s have"} no recorded checking date, so ` +
      `${undated === 1 ? "its" : "their"} timeliness is unknown and ${undated === 1 ? "it is" : "they are"} ` +
      `excluded from the teacher's figures rather than counted against her.`);
  }
  if (disputed) {
    notes.push(`On ${disputed} notebook${disputed === 1 ? "" : "s"} a checking observation is contradicted ` +
      `by the date recorded beside it. One of the two entries is wrong, so ` +
      `${disputed === 1 ? "it is" : "they are"} shown but not counted — please confirm which is correct.`);
  }
  if (notes.length) {
    y -= 4;
    for (const n of notes) {
      for (const line of wrapText(n, contentW - 12, 8)) {
        ensure(13);
        pdf.text(line, M + 10, y, { size: 8, color: GREY });
        y -= 11;
      }
      y -= 3;
    }
  }

  heading("Overall Observation");
  para(r.finalObservation || "—");

  heading("Recommended Corrective Actions");
  if (r.recs.length) {
    for (const rec of r.recs) {
      const lines = wrapText(rec, contentW - 16, 9.5);
      lines.forEach((line, i) => {
        ensure(15);
        if (i === 0) pdf.text("•", M + 2, y, { size: 9.5, color: TEAL });
        pdf.text(line, M + 16, y, { size: 9.5 });
        y -= 13.5;
      });
      y -= 2;
    }
  } else {
    para("No corrective action is required at this stage.");
  }

  heading("Principal Summary");
  para(r.principalSummary || "—");

  footer();
  return pdf.build();
}

/** Trim to fit a column, with an ellipsis, so a long name cannot run into the next field. */
function clip(s: string, maxWidth: number, size: number): string {
  const t = String(s ?? "");
  if (textWidth(t, size) <= maxWidth) return t;
  let out = "";
  for (const ch of t) {
    if (textWidth(`${out}${ch}…`, size) > maxWidth) break;
    out += ch;
  }
  return `${out}…`;
}

/** A filename someone can find again in their downloads folder. */
export function reportFileName(r: PdfReport): string {
  const safe = (s: string) => String(s ?? "").replace(/[^A-Za-z0-9]+/g, "-").replace(/^-|-$/g, "");
  return `NQAS-${safe(r.teacher) || "Report"}-${safe(r.subject)}-${r.date}.pdf`;
}
