"use client";
import { useState } from "react";
import { STATUS_META, studentTag, tagColor, CLASS_BAND_LABEL, type ClassBand } from "@/lib/observations";

export interface ReportStudent {
  name: string;
  days: number | null;
  remark: string;
  // New reports carry statusTag; older reports carry cpi + band. Both are
  // optional here so ReportView can render either vintage correctly.
  statusTag?: string;
  cpi?: string;
  band?: string;
}
export interface ReportData {
  meta: { campus: string; coordinatorName: string; date: string };
  academic: { teacher: string; cls: string; subject: string; classBand?: ClassBand };
  students: ReportStudent[];
  recs: string[];
  finalObservation: string;
  principalSummary: string;
  engine: string;
}

function statusLabel(s: ReportStudent): string {
  const tag = studentTag(s);
  const emoji = (STATUS_META as Record<string, { emoji: string }>)[tag]?.emoji;
  return emoji ? `${emoji} ${tag}` : tag;
}

function wordHTML(r: ReportData, watermark: string) {
  const esc = (s: unknown) => String(s ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  const rows = r.students.map((s) =>
    `<tr><td style="border:1px solid #ccc;padding:6px;">${esc(s.name || "—")}</td><td style="border:1px solid #ccc;padding:6px;text-align:center;">${s.days == null ? "—" : s.days}</td><td style="border:1px solid #ccc;padding:6px;text-align:center;">${esc(statusLabel(s))}</td><td style="border:1px solid #ccc;padding:6px;">${esc(s.remark)}</td></tr>`).join("");
  const classBandRow = r.academic.classBand
    ? `<tr><td><b>Class Band:</b> ${esc(CLASS_BAND_LABEL[r.academic.classBand])}</td><td></td><td></td></tr>` : "";
  return `<!DOCTYPE html><html><head><meta charset="utf-8"></head><body style="font-family:Georgia,serif;color:#20242e;position:relative;">
  <div style="position:relative;">
    <img src="${watermark}" style="position:absolute;top:180px;left:50%;transform:translateX(-50%);width:340px;opacity:0.05;z-index:0;" />
    <div style="position:relative;z-index:1;">
    <div style="border-bottom:3px solid #026874;padding:14px 18px;display:flex;align-items:center;gap:14px;">
      <div>
        <div style="font-size:19px;font-weight:bold;color:#0A3F6B;font-family:Georgia,serif;">Krishna Vikash Group of CBSE Schools</div>
        <div style="font-size:12px;color:#026874;font-weight:600;">${esc(r.meta.campus)}</div>
      </div>
    </div>
    <h2 style="text-align:center;color:#0A3F6B;margin:16px 0 4px;">Notebook Verification Report</h2>
    <table style="width:100%;font-size:13px;margin:10px 0;"><tr><td><b>Teacher:</b> ${esc(r.academic.teacher)}</td><td><b>Class:</b> ${esc(r.academic.cls)}</td><td><b>Subject:</b> ${esc(r.academic.subject)}</td></tr>
    <tr><td><b>Date:</b> ${esc(r.meta.date)}</td><td><b>Coordinator:</b> ${esc(r.meta.coordinatorName)}</td><td><b>Samples:</b> ${r.students.length}</td></tr>${classBandRow}</table>
    <table style="width:100%;border-collapse:collapse;font-size:12px;font-family:Arial,sans-serif;"><thead><tr style="background:#0A3F6B;color:#fff;"><th style="border:1px solid #ccc;padding:6px;text-align:left;">Student</th><th style="border:1px solid #ccc;padding:6px;">Days Since Checked</th><th style="border:1px solid #ccc;padding:6px;">Status</th><th style="border:1px solid #ccc;padding:6px;text-align:left;">Observations</th></tr></thead><tbody>${rows}</tbody></table>
    <h3 style="color:#026874;margin:16px 0 4px;">Final Observation</h3><p style="font-size:13px;line-height:1.6;">${esc(r.finalObservation)}</p>
    <h3 style="color:#026874;margin:16px 0 4px;">Recommended Corrective Actions</h3><ul style="font-size:13px;">${r.recs.map((x) => `<li>${esc(x)}</li>`).join("") || "<li>No corrective action is required at this stage.</li>"}</ul>
    <h3 style="color:#026874;margin:16px 0 4px;">Principal Summary</h3><p style="font-size:13px;line-height:1.6;">${esc(r.principalSummary)}</p>
    <div style="margin-top:24px;font-size:12px;color:#5b616e;border-top:1px solid #ccc;padding-top:6px;">Academics, ${esc(r.meta.campus)} — generated by NQAS</div>
    </div>
  </div>
  </body></html>`;
}

export default function ReportView({ r }: { r: ReportData }) {
  const [copied, setCopied] = useState(false);

  const downloadWord = async () => {
    const logoRes = await fetch("/logo-symbol.png");
    const logoBlob = await logoRes.blob();
    const watermark: string = await new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.onerror = reject;
      reader.readAsDataURL(logoBlob);
    });
    const blob = new Blob(["﻿", wordHTML(r, watermark)], { type: "application/msword" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = `NQAS_${(r.academic.subject || "Report").replace(/\s+/g, "_")}_${r.meta.date}.doc`;
    document.body.appendChild(a); a.click(); document.body.removeChild(a); URL.revokeObjectURL(url);
  };
  const copyWA = async () => {
    const txt = `*Notebook Verification — ${r.academic.subject} (${r.academic.cls})*\nCampus: ${r.meta.campus}\nTeacher: ${r.academic.teacher}\nDate: ${r.meta.date}\nSamples: ${r.students.length}\n\n${r.principalSummary}`;
    try { await navigator.clipboard.writeText(txt); setCopied(true); setTimeout(() => setCopied(false), 1800); } catch { /* ignore */ }
  };

  return (
    <div>
      <div className="no-print" style={{ display: "flex", gap: 8, marginBottom: 12, flexWrap: "wrap", alignItems: "center" }}>
        <button className="btn btn-accent btn-sm" onClick={downloadWord}>⬇ Word (.doc)</button>
        <button className="btn btn-ghost btn-sm" onClick={() => window.print()}>🖨 Print / PDF</button>
        <button className="btn btn-ghost btn-sm" onClick={copyWA}>{copied ? "✓ Copied" : "WhatsApp summary"}</button>
        <span className="muted" style={{ marginLeft: "auto", fontSize: 11.5 }}>
          narrative: <b style={{ color: r.engine === "ai" ? "var(--teal)" : "var(--sub)" }}>{r.engine === "ai" ? "AI" : "deterministic"}</b>
        </span>
      </div>
      <div className="report report-print" style={{ position: "relative", overflow: "hidden" }}>
        <div
          aria-hidden="true"
          style={{
            position: "absolute", top: "22%", left: "50%", transform: "translate(-50%, 0)",
            width: 340, height: 340, backgroundImage: "url(/logo-symbol.png)",
            backgroundSize: "contain", backgroundRepeat: "no-repeat", backgroundPosition: "center",
            opacity: 0.05, pointerEvents: "none", zIndex: 0,
          }}
        />
        <div style={{ position: "relative", zIndex: 1 }}>
          <div className="report-hd" style={{ display: "flex", alignItems: "center", gap: 12 }}>
            <img src="/logo-symbol.png" alt="" width={40} height={40} style={{ flexShrink: 0, borderRadius: "50%", background: "#fff", padding: 2, border: "1.5px solid var(--gold-soft)" }} />
            <div>
              <div style={{ fontSize: 17, fontWeight: 700, fontFamily: "var(--font-ui)" }}>Krishna Vikash Group of CBSE Schools</div>
              <div style={{ fontSize: 12, color: "var(--gold-soft)" }}>{r.meta.campus}</div>
            </div>
          </div>
          <div className="report-body">
            <h1>Notebook Verification Report</h1>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "4px 18px", fontSize: 13, marginBottom: 14 }}>
              <div><b>Teacher:</b> {r.academic.teacher}</div><div><b>Class:</b> {r.academic.cls}</div><div><b>Subject:</b> {r.academic.subject}</div>
              <div><b>Date:</b> {r.meta.date}</div><div><b>Coordinator:</b> {r.meta.coordinatorName}</div><div><b>Samples:</b> {r.students.length}</div>
              {r.academic.classBand && <div><b>Class Band:</b> {CLASS_BAND_LABEL[r.academic.classBand]}</div>}
            </div>
            <div className="scroll-x">
              <table className="rt">
                <thead><tr><th>Student</th><th>Days</th><th>Status</th><th style={{ textAlign: "left" }}>Observations</th></tr></thead>
                <tbody>{r.students.map((s, i) => (
                  <tr key={i} style={{ background: i % 2 ? "#fafaf7" : "#fff" }}>
                    <td>{s.name || "—"}</td><td style={{ textAlign: "center" }}>{s.days ?? "—"}</td>
                    <td style={{ textAlign: "center" }}>
                      <span className="band" style={{ background: tagColor(studentTag(s)) }}>{statusLabel(s)}</span>
                    </td>
                    <td>{s.remark}</td>
                  </tr>))}</tbody>
              </table>
            </div>
            <h3>Final Observation</h3><p style={{ margin: "0 0 13px" }}>{r.finalObservation}</p>
            <h3>Recommended Corrective Actions</h3>
            {r.recs.length ? <ul style={{ margin: "0 0 13px", paddingLeft: 20 }}>{r.recs.map((x, i) => <li key={i} style={{ marginBottom: 4 }}>{x}</li>)}</ul>
              : <p style={{ margin: "0 0 13px" }}>No corrective action is required at this stage.</p>}
            <h3>Principal Summary</h3><p style={{ margin: 0 }}>{r.principalSummary}</p>
            <div style={{ marginTop: 18, fontSize: 12, color: "var(--sub)", borderTop: "1px solid var(--line)", paddingTop: 7 }}>
              Academics, {r.meta.campus} — generated by NQAS
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// Legacy helper, kept for any old callers; new code should use studentTag() + tagColor().
export function bandChip(b: string) {
  return <span className="band" style={{ background: tagColor(b) }}>{b}</span>;
}
