"use client";
import { useState } from "react";
import { BAND_META } from "@/lib/observations";

export interface ReportData {
  meta: { campus: string; coordinatorName: string; date: string };
  academic: { teacher: string; cls: string; subject: string };
  students: { name: string; days: number | null; cpi: string; band: string; remark: string }[];
  recs: string[];
  finalObservation: string;
  principalSummary: string;
  engine: string;
}

function wordHTML(r: ReportData) {
  const esc = (s: unknown) => String(s ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  const rows = r.students.map((s) =>
    `<tr><td style="border:1px solid #ccc;padding:6px;">${esc(s.name || "—")}</td><td style="border:1px solid #ccc;padding:6px;text-align:center;">${s.days == null ? "—" : s.days}</td><td style="border:1px solid #ccc;padding:6px;text-align:center;">${esc(s.cpi)}</td><td style="border:1px solid #ccc;padding:6px;">${esc(s.remark)}</td></tr>`).join("");
  return `<!DOCTYPE html><html><head><meta charset="utf-8"></head><body style="font-family:Georgia,serif;color:#20242e;">
  <div style="background:#1B2A4A;color:#fff;padding:14px 18px;"><div style="font-size:18px;font-weight:bold;">Krishna Vikash Group of Schools</div><div style="font-size:12px;color:#cdd5e5;">${esc(r.meta.campus)}</div></div>
  <h2 style="text-align:center;color:#1B2A4A;margin:16px 0 4px;">Notebook Verification Report</h2>
  <table style="width:100%;font-size:13px;margin:10px 0;"><tr><td><b>Teacher:</b> ${esc(r.academic.teacher)}</td><td><b>Class:</b> ${esc(r.academic.cls)}</td><td><b>Subject:</b> ${esc(r.academic.subject)}</td></tr>
  <tr><td><b>Date:</b> ${esc(r.meta.date)}</td><td><b>Coordinator:</b> ${esc(r.meta.coordinatorName)}</td><td><b>Samples:</b> ${r.students.length}</td></tr></table>
  <table style="width:100%;border-collapse:collapse;font-size:12px;font-family:Arial,sans-serif;"><thead><tr style="background:#1C3D5A;color:#fff;"><th style="border:1px solid #ccc;padding:6px;text-align:left;">Student</th><th style="border:1px solid #ccc;padding:6px;">Days Since Checked</th><th style="border:1px solid #ccc;padding:6px;">CPI</th><th style="border:1px solid #ccc;padding:6px;text-align:left;">Observations</th></tr></thead><tbody>${rows}</tbody></table>
  <h3 style="color:#1C5A6B;margin:16px 0 4px;">Final Observation</h3><p style="font-size:13px;line-height:1.6;">${esc(r.finalObservation)}</p>
  <h3 style="color:#1C5A6B;margin:16px 0 4px;">Recommended Corrective Actions</h3><ul style="font-size:13px;">${r.recs.map((x) => `<li>${esc(x)}</li>`).join("") || "<li>No corrective action is required at this stage.</li>"}</ul>
  <h3 style="color:#1C5A6B;margin:16px 0 4px;">Principal Summary</h3><p style="font-size:13px;line-height:1.6;">${esc(r.principalSummary)}</p>
  <div style="margin-top:24px;font-size:12px;color:#5b616e;border-top:1px solid #ccc;padding-top:6px;">Academics, ${esc(r.meta.campus)} — generated by NQAS</div></body></html>`;
}

export default function ReportView({ r }: { r: ReportData }) {
  const [copied, setCopied] = useState(false);

  const downloadWord = () => {
    const blob = new Blob(["\ufeff", wordHTML(r)], { type: "application/msword" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = `NQAS_${(r.academic.subject || "Report").replace(/\s+/g, "_")}_${r.meta.date}.doc`;
    document.body.appendChild(a); a.click(); document.body.removeChild(a); URL.revokeObjectURL(url);
  };
  const copyWA = async () => {
    const txt = `*Notebook Verification — ${r.academic.subject} (${r.academic.cls})*\nCampus: ${r.meta.campus}\nTeacher: ${r.academic.teacher}\nDate: ${r.meta.date}\nSamples: ${r.students.length}\n\n${r.principalSummary}`;
    try { await navigator.clipboard.writeText(txt); setCopied(true); setTimeout(() => setCopied(false), 1800); } catch { /* ignore */ }
  };

  return (
    <div>
      <div className="no-print" style={{ display: "flex", gap: 8, marginBottom: 12, flexWrap: "wrap", alignItems: "center" }}>
        <button className="btn btn-accent btn-sm" onClick={downloadWord}>⬇ Word (.doc)</button>
        <button className="btn btn-ghost btn-sm" onClick={() => window.print()}>🖨 Print / PDF</button>
        <button className="btn btn-ghost btn-sm" onClick={copyWA}>{copied ? "✓ Copied" : "WhatsApp summary"}</button>
        <span className="muted" style={{ marginLeft: "auto", fontSize: 11.5 }}>
          narrative: <b style={{ color: r.engine === "ai" ? "var(--teal)" : "var(--sub)" }}>{r.engine === "ai" ? "AI" : "deterministic"}</b>
        </span>
      </div>
      <div className="report report-print">
        <div className="report-hd">
          <div style={{ fontSize: 17, fontWeight: 700 }}>Krishna Vikash Group of Schools</div>
          <div style={{ fontSize: 12, color: "#cdd5e5" }}>{r.meta.campus}</div>
        </div>
        <div className="report-body">
          <h1>Notebook Verification Report</h1>
          <div style={{ display: "flex", flexWrap: "wrap", gap: "4px 18px", fontSize: 13, marginBottom: 14 }}>
            <div><b>Teacher:</b> {r.academic.teacher}</div><div><b>Class:</b> {r.academic.cls}</div><div><b>Subject:</b> {r.academic.subject}</div>
            <div><b>Date:</b> {r.meta.date}</div><div><b>Coordinator:</b> {r.meta.coordinatorName}</div><div><b>Samples:</b> {r.students.length}</div>
          </div>
          <div className="scroll-x">
            <table className="rt">
              <thead><tr><th>Student</th><th>Days</th><th>CPI</th><th style={{ textAlign: "left" }}>Observations</th></tr></thead>
              <tbody>{r.students.map((s, i) => (
                <tr key={i} style={{ background: i % 2 ? "#fafaf7" : "#fff" }}>
                  <td>{s.name || "—"}</td><td style={{ textAlign: "center" }}>{s.days ?? "—"}</td>
                  <td style={{ textAlign: "center" }}>{s.cpi}</td><td>{s.remark}</td>
                </tr>))}</tbody>
            </table>
          </div>
          <h3>Final Observation</h3><p style={{ margin: "0 0 13px" }}>{r.finalObservation}</p>
          <h3>Recommended Corrective Actions</h3>
          {r.recs.length ? <ul style={{ margin: "0 0 13px", paddingLeft: 20 }}>{r.recs.map((x, i) => <li key={i} style={{ marginBottom: 4 }}>{x}</li>)}</ul>
            : <p style={{ margin: "0 0 13px" }}>No corrective action is required at this stage.</p>}
          <h3>Principal Summary</h3><p style={{ margin: 0 }}>{r.principalSummary}</p>
          <div style={{ marginTop: 18, fontSize: 12, color: "var(--sub)", borderTop: "1px solid var(--line)", paddingTop: 7 }}>
            Academics, {r.meta.campus} — generated by NQAS
          </div>
        </div>
      </div>
    </div>
  );
}

export function bandChip(b: string) {
  const color = (BAND_META as Record<string, { color: string }>)[b]?.color || "#5b616e";
  return <span className="band" style={{ background: color }}>{b}</span>;
}
